/**:
  ros__parameters:
# yolo inferenece target
    det_class1 : "cat"
    det_class2 : "dog"
    det_class3 : "horse"
    det_class4 : "cow"
# a*x + b for angle_x
    k_a : -25.000
    k_b : 2.0
# yolo parameters
    yolo_model: "yolo11n.pt"
    input_rgb_topic: "/image_raw"
    publish_annotated_image: True
    rgb_topic: "/yolo_ros/rgb_image"
    annotated_topic: "/yolo_ros/annotated_image"
    detailed_topic: "/yolo_ros/detection_result"
    threshold: 0.5
    device: "cpu"