/**:
  ros__parameters:
# yolo inferenece target
    det_class1 : "cookie"
    det_class2 : "cupcake"
    det_class3 : "donut"
    det_class4 : "shortcake"
# a*x + b for angle_x
    k_a : -29.000
    k_b : 1.0
